
version: '3.8'

services:
  app:
    # Membangun image dari Dockerfile di direktori saat ini
    build: .
    # Memetakan port 3000 di mesin Anda ke port 3000 di dalam container
    ports:
      - "3000:3000"
    # Secara opsional, Anda bisa memberikan nama untuk container agar mudah dikenali
    container_name: my-node-app
